Repository LikeLion-at-DGU/moin_backend, pull requests merged in 2023-08, with the labels that each got.

#5 ✨db server migrate
  moin/settings.py
Labels: enhancement

#20 🐛 fix : suggetions
  suggestion/models.py
Labels: safe

#21 Update README.md
  README.md
Labels: safe

#22 deploy : cicd test 2
  README.md
Labels: safe

#26 deploy: CICD test 3차
  README.md
Labels: safe

#30 depoly : 2차 메인 반영
  README.md
  community/models.py
  main/models.py
  moin/settings.py
  notice/models.py
  suggestion/models.py
Labels: safe

#32 🐛 fix : engine 환경변수명 반영
  .github/workflows/django.yml
Labels: safe

#34 ✨ feat : slash 코드 추가
  moin/settings.py
Labels: 영신, safe

#36 ✨ feat : 인공지능 목록 구현
  main/serializers.py
  main/views.py
  moin/settings.py
  requirements.txt
Labels: safe

#37 🚑 fix : settings 관련 수정
  moin/settings.py
Labels: safe

#38 🚑 fix : user 모델 관련 수정
  community/migrations/0001_initial.py
  main/migrations/0001_initial.py
  main/serializers.py
  moin/urls.py
  notice/migrations/0001_initial.py
  suggestion/migrations/0001_initial.py
  user/migrations/0001_initial.py
  user/models.py
  user/serializers.py
  user/urls.py
  user/views.py
Labels: safe

#39 🚑 fix : gitignore 추가
  .gitignore
Labels: safe

#40 🔥 migration 삭제
  community/migrations/0001_initial.py
  community/migrations/__init__.py
  main/migrations/0001_initial.py
  main/migrations/__init__.py
  notice/migrations/0001_initial.py
  notice/migrations/__init__.py
  suggestion/migrations/0001_initial.py
  suggestion/migrations/__init__.py
  user/migrations/0001_initial.py
  user/migrations/__init__.py
Labels: safe

#41 ✨ feat : 좋아요
  main/models.py
  main/paginations.py
  main/serializers.py
  main/urls.py
  main/views.py
Labels: safe

#48 ✨feat : 댓글 기능 1차 구현
  main/models.py
  main/permissions.py
  main/serializers.py
  main/urls.py
  main/views.py
Labels: safe

#70 ✨ feat : [마이페이지] 마이페이지 기능 구현 완료
  moin/settings.py
  moin/urls.py
  mypage/__init__.py
  mypage/admin.py
  mypage/apps.py
  mypage/models.py
  mypage/tests.py
  mypage/views.py
  user/models.py
  user/serializers.py
  user/urls.py
  user/views.py
Labels: safe

#72 ✨feat : 구글 로그인
  requirements.txt
  user/oauth.py
  user/urls.py
Labels: safe

#73 ✨ feat : 비밀번호 변경 시 기존 비밀번호 입력 받기 추가
  user/serializers.py
  user/urls.py
  user/views.py
Labels: safe

#74 ✨ feat : 카카오 로그인 구현
  user/oauth.py
  user/urls.py
Labels: safe

#85 🩹 fix : 비회원 내 평점 0점 반환
  main/serializers.py
Labels: safe

#88 Fix : 좋아요 유무 관련 변경
  main/serializers.py
  main/views.py
Labels: safe

#89 🩹 fix : url 슬래쉬 다시 수정^^
  community/urls.py
  suggestion/urls.py
  user/serializers.py
  user/urls.py
  user/views.py
Labels: safe

#90 🩹 fix : 평가가 없을 때 평균평점 null->0.0 반환
  main/serializers.py
  main/views.py
Labels: safe

#93 ✨ feat : 인공지능 정보 새로운 모델 생성
  main/models.py
  main/serializers.py
  main/urls.py
  main/views.py
Labels: safe

#91 ✨ feat : 마이페이지 페이지네이션 구현
  community/serializers.py
  community/urls.py
  community/views.py
  user/paginations.py
  user/views.py
Labels: safe

#95 ✨ feat : 건의사항 댓글 리스트 api 추가
  community/serializers.py
  suggestion/urls.py
  suggestion/views.py
  user/views.py
Labels: safe

#94 🩹 fix : 오타 수정
  main/models.py
  main/serializers.py
  main/views.py
Labels: safe

#96 ✨ feat : csrf 관련 추가
  moin/settings.py
Labels: safe

#97 ✨ feat : admin 모델 추가
  community/admin.py
  community/serializers.py
  main/admin.py
  main/serializers.py
  user/views.py
Labels: safe

#98 🩹 fix : oauth BASE url 수정
  user/oauth.py
Labels: safe

#102 🩹 fix : 키워드 수정
  main/views.py
Labels: safe

#103 Update django.yml - gmail sending mail(.env)
  .github/workflows/django.yml
Labels: safe

#104 🚀Deploy : CORS 추가
  moin/settings.py
Labels: safe

#106 🚀depoly: 6차 메인 반영
  .github/workflows/django.yml
  .gitignore
  README.md
  community/admin.py
  community/models.py
  community/paginations.py
  community/permissions.py
  community/serializers.py
  community/urls.py
  community/views.py
  main/admin.py
  main/models.py
  main/paginations.py
  main/permissions.py
  main/serializers.py
  main/urls.py
  main/views.py
  moin/settings.py
  moin/urls.py
  mypage/__init__.py
  mypage/admin.py
  mypage/apps.py
  mypage/models.py
  mypage/tests.py
  mypage/views.py
  notice/admin.py
  notice/models.py
  notice/paginations.py
  notice/serializers.py
  notice/urls.py
  notice/views.py
  requirements.txt
  suggestion/admin.py
  suggestion/models.py
  suggestion/paginations.py
  suggestion/permissions.py
  suggestion/serializers.py
  suggestion/urls.py
  suggestion/views.py
  user/admin.py
  user/models.py
  user/oauth.py
  user/paginations.py
  user/serializers.py
  user/urls.py
  user/views.py
Labels: safe

#107 🚀Deploy : 7차 테스트
  moin/settings.py
Labels: enhancement, safe

#108 ✨ feat : 꿀팁 리스트 ai 검색 추가
  community/views.py
Labels: safe

#109 🚀Deploy : 8차 테스트
  README.md
Labels: safe

#111 ✨ feat : 커뮤니티 이미지 업로드 추가
  community/urls.py
  community/utils.py
Labels: safe

#112 🩹 fix : 경로 간단하게 수정
  community/urls.py
  community/utils.py
Labels: safe

#113 🩹 fix : ai detail 댓글 최신순 적용
  main/views.py
Labels: safe

#114 🩹 fix : 최신순 기준 created_at으로 변경
  community/views.py
  main/views.py
  notice/views.py
  suggestion/views.py
Labels: safe

#115 🩹 fix : 커뮤니티 좋아요
  community/serializers.py
Labels: safe

#116 🩹 fix : 평점 관련 수정
  main/views.py
Labels: safe

#117 🚑 fix : 구글 로그인 에러 메세지 출력
  user/oauth.py
Labels: safe

#118 🚑 feat : 오류 메세지 저장
  user/oauth.py
Labels: safe

#120 🩹 fix : 소셜 로그인 url 발버둥
  user/oauth.py
Labels: safe

#119 ✨ feat : 마이페이지 api 찢기 - 게시물 중 카테고리 각각 보는 거 완료
  community/serializers.py
  community/views.py
  main/serializers.py
  suggestion/serializers.py
  user/urls.py
  user/views.py
Labels: safe

#124 🩹 fix : 내 게시물 목록 likes_cnt 추가
  community/serializers.py
  user/views.py
Labels: safe

#125 🩹 fix : 댓글 updated_at 수정
  main/models.py
  main/views.py
Labels: safe

#126 ✨ feat : suggestion, community ai str로 변경
  community/serializers.py
  suggestion/serializers.py
Labels: safe

#127 🩹 fix : 사진 업로드 moin폴더로 이동 + appname받아서 저장
  community/urls.py
  moin/urls.py
  moin/utils.py
Labels: safe

#128 🩹 fix : 건의사항 두 가지 수정
  community/serializers.py
  suggestion/models.py
  suggestion/serializers.py
Labels: safe

#129 🩹 fix : 건의사항 ai blank도 되게 수정
  community/serializers.py
  suggestion/serializers.py
Labels: safe

#130 🩹 fix : updated_at 필드 수정
  community/models.py
  community/views.py
  notice/models.py
  notice/views.py
Labels: safe

#132 ✨ feat : 커뮤니티 목록에서도 view_cnt 추가
  community/serializers.py
  community/views.py
  user/paginations.py
  user/views.py
Labels: safe

#134 ✨ feat : [마이페이지] 내가 작성한 게시물 커뮤+건의 구현 완
  community/serializers.py
  user/views.py
Labels: safe

#135 🩹 fix : [마이페이지] 좋아요 관련 몇 가지 수정
  community/serializers.py
  user/urls.py
  user/views.py
Labels: safe

#136 🩹 fix : 내가 좋아요 한 커뮤니티 ai 없을 시 기타로 뜨게 설정
  community/serializers.py
Labels: safe

#137 🩹 fix : ai의 url 필드 종류 수정
  main/models.py
Labels: safe

#138 🩹 fix : 내 댓글 ai title 보이게
  main/serializers.py
Labels: safe

#139 🩹 fix : [마이페이지] 내 전체 댓글 커뮤는 id, ai는 title 보이게
  community/serializers.py
  user/views.py
Labels: safe

#140 🩹 fix : 이메일 재설정 url 수정
  user/views.py
Labels: safe

#141 ✨ feat : 모든 api에 대하여 회원, 비회원 모두 중복 호출 방지
  moin/settings.py
Labels: safe

#142 🩹 fix : 수정
  moin/settings.py
Labels: safe

#144 test: CICD
  README.md
Labels: safe

#146 🩹 fix : list 2배수 수정
  main/views.py
Labels: safe

#147 ✨ feat : AI eng 추가
  main/models.py
  main/serializers.py
  main/urls.py
  main/views.py
Labels: safe

#148 🩹 fix : eng info에서 eng_title 삭제
  main/serializers.py
Labels: safe
